test 4 for precommit workflow

diff --git a/.github/workflows/pre-commit.yaml b/.github/workflows/pre-commit.yaml
--- a/.github/workflows/pre-commit.yaml
+++ b/.github/workflows/pre-commit.yaml
@@ -23,13 +23,13 @@ jobs:
               run: |
                 pip install mkdocs
                 pip install 'mkdocs-spellcheck[all]'
-                OUTPUT=$(mkdocs build)
+                mkdocs build || { echo "MkDocs build failed"; exit 1; }
 
             - name: Run mkdocs spellcheck
               id: spellcheck
               run: |
                 echo "You should see this"
-                OUTPUT=$(mkdocs build)
+                OUTPUT=$(mkdocs build 2>&1)
                 echo "Hello"
                 echo $OUTPUT
                 if echo "${OUTPUT}" | grep -q "misspelled"; then
